Remove `_dropck` flag from `SendError`
faern/oneshot pull request #19
Opened 2022-08-04 11:11 UTC by Nilstrieb

The nomicon has been outdated about this since 2015,
see rust-lang/nomicon#363 for the update. 
We don't need to tell dropck that we are owning a T as it
can already infer that from the generic parameter in the drop impl.

cc @Cassy343 who added it

2022-08-04 14:40 UTC, Cassy343 commented
Could this be modified to just remove the comment and explain instead that we'll need something like this if a `#[may_dangle]`-like thing ever gets stabilized?

2022-08-14 09:39 UTC, faern requested changes
Looks good overall. Please also remove the `_dropck` field from `Sender` and `Receiver` then. They shoud be equally not needed.

I don't think we need to drag these along just in case `#[may_dangle]` becomes a thing. Because if that becomes a thing I'm assuming it would be opt in, and any such opting in would need to make sure the ownership is correctly marked at that point.

2022-08-14 09:57 UTC, faern commented
Looks like you force pushed a new commit that is identical?

2022-08-14 09:58 UTC, Nilstrieb commented
oh

2022-08-14 10:04 UTC, merged

2022-08-14 10:05 UTC, faern commented
Thank you for the contribution!

2022-08-14 10:07 UTC, faern commented
Aah. It should have been removed from the changelog as well! https://github.com/faern/oneshot/blob/3cee01f3ff91afa7691357494f87cbd3d2727446/CHANGELOG.md#fixed

I'll do that directly.

2022-08-14 10:09 UTC, faern commented
https://github.com/faern/oneshot/commit/b84c62462a32f1ace2713fbf1eb09bee15dea6af